#!/usr/bin/env bash
# a Bash script that will display information about subdomains.

domain_info () {
    domain="$1"
    subdomain="$2"
    subdomains=("www" "lb-01" "web-01" "web-02")

    if [ "$subdomain" ]; then
        IP=$(dig "$subdomain"."$domain" | awk '/^;; ANSWER SECTION:$/ { getline; print $5 }')
        echo "The subdomain $subdomain is an A record and points to $IP"
    else
        for sub in "${subdomains[@]}"; do
            IP=$(dig "$sub.$domain" | awk '/^;; ANSWER SECTION:$/ { getline; print $5 }')
            echo "The subdomain $sub is an A record and points to $IP"
        done
    fi
}
domain_info "$1" "$2"
