#!/usr/bin/env bash
# Redirection

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Set up the Nginx configuration for the redirection
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root    /var/www/html;
    index   index.nginx-debian.html;
    location /redirect_me {
	return 301 https://github.com/fatimazaarate;
}
}" > /etc/nginx/sites-available/default

service nginx restart