#!/usr/bin/env bash
# Redirection

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Set up the Nginx configuration for the redirection
new_line="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/fatimazaarate permanent;"
sed -i "/server_name _;/a $new_line" /etc/nginx/sites-available/default

# Set up the Nginx configuration for the Not found page 404
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
new_string="server_name _;\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-available/default
service nginx restart