#!/usr/bin/env bash
# Installing and configuring HAproxy on your lb-01 server

apt-get update
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8
apt-get install -y haproxy

echo "
frontend web-frontend
	bind *:80
	mode http
	default_backend web-backend
backend web-backend
	server firstHost 34.224.3.13:80 check
	server secondHost 3.83.18.210:80 check
	balance roundrobin
	mode http
" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy
sudo service haproxy restart
